apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pv-manager-binding
subjects:
- kind: ServiceAccount
  name: azdev-sa-b94d18
  namespace: workshop
roleRef:
  kind: ClusterRole
  name: pv-manager
  apiGroup: rbac.authorization.k8s.io
