apiVersion: v1
kind: Secret
metadata: 
  namespace: {{ .Values.namespace }}
  name: {{ .Values.secret.name }}
type: {{ .Values.secret.type }}
data:  
  password: {{ .Values.secret.password }}  # "password123"
  username: {{ .Values.secret.username }}  # "admin"
  connection_string: {{ .Values.secret.connectionstring }}  # "mongodb://admin:password123@mongodb-svc:27017/todo?authSource=admin"
