apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.app.labels }}                   # Ensure the label matches your MongoDB deployment
  ports:
  - name: {{ .Values.service.name }}
    protocol: TCP
    port: 27017                     # Expose the service on port 27017
    targetPort: 27017               # Redirect traffic to MongoDB container port
  type: {{ .Values.service.type }}               # Expose the service externally via LoadBalancer
