apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.app }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 5001            # Expose the service on port 5001
      targetPort: 5001      # Redirect traffic to port 5001 in the container
      protocol: TCP
  type: {{ .Values.service.type }}         # Expose the service externally via LoadBalancer
  selector:
    role: {{ .Values.deployment.app }}                # Matches the role label of your pods
